# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea57f930d0fe3224599cb0075072be9f4008940f376844a6d3d41109c996df2ef89ada7abdc53b9ccec4ff53893f8397a79b870c7ccfedee959d9c5cec759aa

test:
  secret_key_base: 8ac1bddfaf16820dad647565e2bbe03feebe8503b76f74bdd9911c7f0a0ee369864afaf505d7d217c662a506bae00a18ca5900a9f1ab10792a26faf7885406cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
